{% set name = "python-gilt" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 812daf3ca98d92764f3116f2b5a6874b07adaacec361614bd2fcecef5f2f94f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gilt = gilt.shell:main
requirements:
  host:
    - python
    - pip
    - setuptools
    - pbr
  run:
    - click
    - colorama
    - fasteners
    - git-url-parse
    - pbr
    - python
    - pyyaml
    - sh

test:
  requires:
    - pip
  imports:
    - gilt
  commands:
    - pip check

about:
  home: https://github.com/metacloud/gilt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: gilt - A GIT layering tool.
  description: |
    Overlay remote repositories and/or files into the destinations
    provided.
  doc_url: https://gilt.readthedocs.io/en/latest/
  dev_url: https://github.com/metacloud/gilt

extra:
  recipe-maintainers:
    - knightdave
