travis:
  secure:
    BINSTAR_TOKEN: EXWKhHnA+5c5epyElXcLwvaalP+OeJBxQ2GBWwZkzpvzrg08T2aMZEc3kgxG4zrZjcE2ZiVGVNbh1fEPAZmI9H+HypUIrqba6xe9Iz6dpYwQ/+U5ybi3iqwtYHwB/JPlMoc+G4MZU2Sb/AwGc9hNVBzB+KBCBteVSQmqT/Zt7bTrNi8ibgDc5YRdfYmzntrmuSbmrdaGMKshjKpGv5/2ZMf7Xp7iECH5UNZbWLQFBsLN/lUakwknTn+MVav4OGHx1/RdPi1hP49xhQLkzA7DpLoGNaSz1OIu41C0zi8jRYW7H3LlqirBUr6IX+NtWM+ApF0f54I47b6hd5hKdFTQhpiSnvbeDEkJN8gZYg/OhE+iLB4/OGAvvTC463q5/t9KkzXuEKEeuhXi2asCPGxDmD5HhUHrzo8Jj+HG3ipHXCScuxULWJJ3nLwzHzwB9hm7Q7+CsctXy5jlkfIwaqTt7FKE6C87U9gqe14ok3TsOGR+sVWOZjzQ2EhDtcnuX+aQya/6E+GXZ/d61upuglWyKlD+Ni91V+pC1DN07zHi0JVQA96rW6fhjsFF1VgkyVjaMKoXDBuwGldf4XNLeBAcnbS+sXTfi9SQGPDtHl95X54WVHeLY/I7zsPntm3MjO52QWZtRdzPF61BmJ7dc8vPFoh75CfOyjwv6mz5Lys8m6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
